# Append 1.3.0 Claim Status menu keys to all lang packs + matching codex.
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "src" / "main" / "resources"
LANGS = [
    "modern_english", "old_english", "spanish_mx", "spanish_ar",
    "portuguese_br", "french_fr", "italian_it", "german_de", "polish_pl",
]

def dump(value):
    if isinstance(value, list):
        return "\n".join(["  - " + yaml_str(line) for line in value])
    return yaml_str(value)

def yaml_str(s):
    if s is None:
        return "''"
    text = str(s)
    if any(c in text for c in ":#{}[],&*!|>'\"%@`") or text.strip() != text or text == "":
        return "'" + text.replace("'", "''") + "'"
    return text

PACKS = {}

PACKS["modern_english"] = {
    "plot_status_gui_title": "&b✦ Claim Status",
    "plot_status_header_title": "&b✦ Claim Status",
    "plot_status_lore": [
        "&7A snapshot of this plot: owner, protections,",
        "&7blessings, growth, ClaimBlocks, and access.",
        " ",
        "&eClick to open.",
    ],
    "plot_status_button_lore": [
        "&7A snapshot of this plot: owner, protections,",
        "&7blessings, growth, ClaimBlocks, and access.",
        " ",
        "&eClick to open.",
    ],
    "plot_status_kind_personal": "&aPersonal plot",
    "plot_status_kind_server": "&bServer / spawn plot",
    "plot_status_owner_line": "&7Owner: &f{OWNER}",
    "plot_status_world_line": "&7World: &f{WORLD}",
    "plot_status_level_line": "&7Plot Level: &b{LEVEL}&7 / &f{MAX}",
    "plot_status_name_line": "&7Name: &f{NAME}",
    "plot_status_protection_title": "&cProtections & Risks",
    "plot_status_blessings_title": "&dActive Blessings",
    "plot_status_blessings_header_line": "&7Active Blessings:",
    "plot_status_blessings_none_line": "&8- None unlocked yet.",
    "plot_status_blessings_footer_line": "&8Only your highest tier of each blessing is shown.",
    "plot_status_territory_title": "&aTerritory & Growth",
    "plot_status_menu_name": "&3✦ AegisGuard Menu",
    "plot_status_territory_rules_line": "&7Territory Rules:",
    "plot_status_territory_hint_line": "&b{MENU} &7→ &b{EXPAND}",
    "plot_status_access_title": "&eAccess Snapshot",
    "plot_status_members_line": "&7Members: &f{COUNT}",
    "plot_status_guests_line": "&7Guest Passes: &f{COUNT}",
    "plot_status_lockdown_on": "&cLockdown: &fActive",
    "plot_status_lockdown_off": "&7Lockdown: &fOff",
    "plot_status_access_hint": [
        "&8Open Roles, Guest Passes, or Lockdown",
        "&8from the main menu to change this.",
    ],
    "plot_status_upkeep_click": "&eClick to pay early.",
    "plot_status_section_overview_name": "&bOverview",
    "plot_status_section_overview_lore": [
        "&7A snapshot of this plot: protections,",
        "&7blessings, growth, and ClaimBlocks.",
    ],
    "plot_status_section_actions_name": "&6Owner Actions",
    "plot_status_section_actions_lore": [
        "&7Merge, transfer, gift ClaimBlocks,",
        "&7or pay upkeep early.",
    ],
    "plot_status_section_combat": "&7Combat & Hostiles:",
    "plot_status_label_pvp": "PvP",
    "plot_status_label_hostile_mobs": "Hostile mobs",
    "plot_status_label_animals_pets": "Animals & pets",
    "plot_status_section_environment": "&7Environment & Access:",
    "plot_status_label_safe_zone": "Safe zone",
    "plot_status_state_enabled": "&aEnabled",
    "plot_status_state_disabled": "&7Disabled",
    "plot_status_label_entry_gate": "Entry gate",
    "plot_status_state_open": "&aOpen",
    "plot_status_state_closed": "&cClosed",
    "plot_status_label_containers": "Containers",
    "plot_status_label_redstone_doors": "Redstone & doors",
    "plot_status_label_vehicles": "Vehicles",
    "plot_status_section_perks": "&7Perks & Services:",
    "plot_status_label_shop_interact": "Market shop interact",
    "plot_status_state_active": "&aEnabled",
    "plot_status_state_inactive": "&7Inactive",
    "plot_status_label_flight": "Flight inside this plot",
    "plot_status_state_protected": "&aProtected",
    "plot_status_state_vulnerable": "&cVulnerable",
    "plot_status_line_bullet": "&f- {LABEL}: {STATE}",
    "plot_status_blessing_effect_format": "{COLOR}✦ &f{EFFECT} &7(Effect &f{TIER}&7)",
    "plot_status_blessing_member_slots_format": "&a✦ &fTrusted member slots: &b+{AMOUNT}",
    "plot_status_blessing_generic_format": "&a✦ &f{TEXT}",
}

PACKS["old_english"] = {
    "plot_status_gui_title": "&b✦ Estate Status",
    "plot_status_header_title": "&b✦ Estate Status",
    "plot_status_lore": [
        "&7Behold the standing of this holding:",
        "&7lordship, wards, boons, growth, and company.",
        " ",
        "&eClick to open.",
    ],
    "plot_status_button_lore": [
        "&7Behold the standing of this holding:",
        "&7lordship, wards, boons, growth, and company.",
        " ",
        "&eClick to open.",
    ],
    "plot_status_kind_personal": "&aPersonal holding",
    "plot_status_kind_server": "&bServer / spawn holding",
    "plot_status_owner_line": "&7Lord: &f{OWNER}",
    "plot_status_world_line": "&7World: &f{WORLD}",
    "plot_status_level_line": "&7Holding Rank: &b{LEVEL}&7 / &f{MAX}",
    "plot_status_name_line": "&7Name: &f{NAME}",
    "plot_status_protection_title": "&cWards & Perils",
    "plot_status_blessings_title": "&dActive Boons",
    "plot_status_blessings_header_line": "&7Active Boons:",
    "plot_status_blessings_none_line": "&8- None yet granted.",
    "plot_status_blessings_footer_line": "&8Only the highest rank of each boon is shown.",
    "plot_status_territory_title": "&aHoldings & Growth",
    "plot_status_menu_name": "&6✦ AegisGuard Menu ✦",
    "plot_status_territory_rules_line": "&7Laws of the Holding:",
    "plot_status_territory_hint_line": "&b{MENU} &7→ &b{EXPAND}",
    "plot_status_access_title": "&eCompany Snapshot",
    "plot_status_members_line": "&7Company: &f{COUNT}",
    "plot_status_guests_line": "&7Guest Passes: &f{COUNT}",
    "plot_status_lockdown_on": "&cLockdown: &fRaised",
    "plot_status_lockdown_off": "&7Lockdown: &fStill",
    "plot_status_access_hint": [
        "&8Open Roles, Guest Passes, or Lockdown",
        "&8from the hall to change this.",
    ],
    "plot_status_upkeep_click": "&eClick to pay tribute early.",
    "plot_status_section_overview_name": "&bOverview",
    "plot_status_section_overview_lore": [
        "&7A ledger of this holding: wards,",
        "&7boons, growth, and ClaimBlocks.",
    ],
    "plot_status_section_actions_name": "&6Lordly Deeds",
    "plot_status_section_actions_lore": [
        "&7Merge, transfer, gift ClaimBlocks,",
        "&7or pay tribute early.",
    ],
    "plot_status_section_combat": "&7Strife & Beasts:",
    "plot_status_label_pvp": "PvP",
    "plot_status_label_hostile_mobs": "Hostile beasts",
    "plot_status_label_animals_pets": "Beasts & companions",
    "plot_status_section_environment": "&7Land & Entry:",
    "plot_status_label_safe_zone": "Safe haven",
    "plot_status_state_enabled": "&aGranted",
    "plot_status_state_disabled": "&7Denied",
    "plot_status_label_entry_gate": "Entry gate",
    "plot_status_state_open": "&aOpen",
    "plot_status_state_closed": "&cSealed",
    "plot_status_label_containers": "Chests",
    "plot_status_label_redstone_doors": "Redstone & doors",
    "plot_status_label_vehicles": "Wagons",
    "plot_status_section_perks": "&7Boons & Services:",
    "plot_status_label_shop_interact": "Market stall touch",
    "plot_status_state_active": "&aGranted",
    "plot_status_state_inactive": "&7Still",
    "plot_status_label_flight": "Flight within this holding",
    "plot_status_state_protected": "&aWarded",
    "plot_status_state_vulnerable": "&cExposed",
    "plot_status_line_bullet": "&f- {LABEL}: {STATE}",
    "plot_status_blessing_effect_format": "{COLOR}✦ &f{EFFECT} &7(Effect &f{TIER}&7)",
    "plot_status_blessing_member_slots_format": "&a✦ &fTrusted company slots: &b+{AMOUNT}",
    "plot_status_blessing_generic_format": "&a✦ &f{TEXT}",
}

PACKS["spanish_mx"] = {
    "plot_status_gui_title": "&b✦ Estado de Parcela",
    "plot_status_header_title": "&b✦ Estado de Parcela",
    "plot_status_lore": [
        "&7Resumen de esta parcela: dueño, protecciones,",
        "&7bendiciones, crecimiento, ClaimBlocks y acceso.",
        " ",
        "&eClic para abrir.",
    ],
    "plot_status_button_lore": [
        "&7Resumen de esta parcela: dueño, protecciones,",
        "&7bendiciones, crecimiento, ClaimBlocks y acceso.",
        " ",
        "&eClic para abrir.",
    ],
    "plot_status_kind_personal": "&aParcela personal",
    "plot_status_kind_server": "&bParcela de servidor / spawn",
    "plot_status_owner_line": "&7Dueño: &f{OWNER}",
    "plot_status_world_line": "&7Mundo: &f{WORLD}",
    "plot_status_level_line": "&7Nivel de parcela: &b{LEVEL}&7 / &f{MAX}",
    "plot_status_name_line": "&7Nombre: &f{NAME}",
    "plot_status_protection_title": "&cProtecciones y riesgos",
    "plot_status_blessings_title": "&dBendiciones activas",
    "plot_status_blessings_header_line": "&7Bendiciones activas:",
    "plot_status_blessings_none_line": "&8- Aún no hay ninguna.",
    "plot_status_blessings_footer_line": "&8Solo se muestra el nivel más alto de cada bendición.",
    "plot_status_territory_title": "&aTerritorio y crecimiento",
    "plot_status_menu_name": "&3✦ Menú AegisGuard",
    "plot_status_territory_rules_line": "&7Reglas de territorio:",
    "plot_status_territory_hint_line": "&b{MENU} &7→ &b{EXPAND}",
    "plot_status_access_title": "&eResumen de acceso",
    "plot_status_members_line": "&7Miembros: &f{COUNT}",
    "plot_status_guests_line": "&7Pases de invitado: &f{COUNT}",
    "plot_status_lockdown_on": "&cLockdown: &fActivo",
    "plot_status_lockdown_off": "&7Lockdown: &fApagado",
    "plot_status_access_hint": [
        "&8Abre Roles, Pases de invitado o Lockdown",
        "&8desde el menú principal para cambiarlo.",
    ],
    "plot_status_upkeep_click": "&eClic para pagar anticipado.",
    "plot_status_section_overview_name": "&bResumen",
    "plot_status_section_overview_lore": [
        "&7Un vistazo de esta parcela: protecciones,",
        "&7bendiciones, crecimiento y ClaimBlocks.",
    ],
    "plot_status_section_actions_name": "&6Acciones del dueño",
    "plot_status_section_actions_lore": [
        "&7Fusiona, transfiere, regala ClaimBlocks",
        "&7o paga el mantenimiento anticipado.",
    ],
    "plot_status_section_combat": "&7Combate y hostiles:",
    "plot_status_label_pvp": "PvP",
    "plot_status_label_hostile_mobs": "Mobs hostiles",
    "plot_status_label_animals_pets": "Animales y mascotas",
    "plot_status_section_environment": "&7Entorno y acceso:",
    "plot_status_label_safe_zone": "Zona segura",
    "plot_status_state_enabled": "&aActivado",
    "plot_status_state_disabled": "&7Desactivado",
    "plot_status_label_entry_gate": "Puerta de entrada",
    "plot_status_state_open": "&aAbierta",
    "plot_status_state_closed": "&cCerrada",
    "plot_status_label_containers": "Contenedores",
    "plot_status_label_redstone_doors": "Redstone y puertas",
    "plot_status_label_vehicles": "Vehículos",
    "plot_status_section_perks": "&7Ventajas y servicios:",
    "plot_status_label_shop_interact": "Interactuar con tiendas",
    "plot_status_state_active": "&aActivado",
    "plot_status_state_inactive": "&7Inactivo",
    "plot_status_label_flight": "Vuelo dentro de esta parcela",
    "plot_status_state_protected": "&aProtegido",
    "plot_status_state_vulnerable": "&cVulnerable",
    "plot_status_line_bullet": "&f- {LABEL}: {STATE}",
    "plot_status_blessing_effect_format": "{COLOR}✦ &f{EFFECT} &7(Efecto &f{TIER}&7)",
    "plot_status_blessing_member_slots_format": "&a✦ &fEspacios de miembros de confianza: &b+{AMOUNT}",
    "plot_status_blessing_generic_format": "&a✦ &f{TEXT}",
}

PACKS["spanish_ar"] = {
    "plot_status_gui_title": "&b✦ Estado de Parcela",
    "plot_status_header_title": "&b✦ Estado de Parcela",
    "plot_status_lore": [
        "&7Resumen de esta parcela: dueño, protecciones,",
        "&7bendiciones, crecimiento, ClaimBlocks y acceso.",
        " ",
        "&eClic para abrir.",
    ],
    "plot_status_button_lore": [
        "&7Resumen de esta parcela: dueño, protecciones,",
        "&7bendiciones, crecimiento, ClaimBlocks y acceso.",
        " ",
        "&eClic para abrir.",
    ],
    "plot_status_kind_personal": "&aParcela personal",
    "plot_status_kind_server": "&bParcela de servidor / spawn",
    "plot_status_owner_line": "&7Dueño: &f{OWNER}",
    "plot_status_world_line": "&7Mundo: &f{WORLD}",
    "plot_status_level_line": "&7Nivel de parcela: &b{LEVEL}&7 / &f{MAX}",
    "plot_status_name_line": "&7Nombre: &f{NAME}",
    "plot_status_protection_title": "&cProtecciones y riesgos",
    "plot_status_blessings_title": "&dBendiciones activas",
    "plot_status_blessings_header_line": "&7Bendiciones activas:",
    "plot_status_blessings_none_line": "&8- Todavía no hay ninguna.",
    "plot_status_blessings_footer_line": "&8Solo se muestra el nivel más alto de cada bendición.",
    "plot_status_territory_title": "&aTerritorio y crecimiento",
    "plot_status_menu_name": "&3✦ Menú AegisGuard",
    "plot_status_territory_rules_line": "&7Reglas de territorio:",
    "plot_status_territory_hint_line": "&b{MENU} &7→ &b{EXPAND}",
    "plot_status_access_title": "&eResumen de acceso",
    "plot_status_members_line": "&7Miembros: &f{COUNT}",
    "plot_status_guests_line": "&7Pases de invitado: &f{COUNT}",
    "plot_status_lockdown_on": "&cLockdown: &fActivo",
    "plot_status_lockdown_off": "&7Lockdown: &fApagado",
    "plot_status_access_hint": [
        "&8Abrí Roles, Pases de invitado o Lockdown",
        "&8desde el menú principal para cambiarlo.",
    ],
    "plot_status_upkeep_click": "&eClic para pagar anticipado.",
    "plot_status_section_overview_name": "&bResumen",
    "plot_status_section_overview_lore": [
        "&7Un vistazo de esta parcela: protecciones,",
        "&7bendiciones, crecimiento y ClaimBlocks.",
    ],
    "plot_status_section_actions_name": "&6Acciones del dueño",
    "plot_status_section_actions_lore": [
        "&7Fusioná, transferí, regalá ClaimBlocks",
        "&7o pagá el mantenimiento anticipado.",
    ],
    "plot_status_section_combat": "&7Combate y hostiles:",
    "plot_status_label_pvp": "PvP",
    "plot_status_label_hostile_mobs": "Mobs hostiles",
    "plot_status_label_animals_pets": "Animales y mascotas",
    "plot_status_section_environment": "&7Entorno y acceso:",
    "plot_status_label_safe_zone": "Zona segura",
    "plot_status_state_enabled": "&aActivado",
    "plot_status_state_disabled": "&7Desactivado",
    "plot_status_label_entry_gate": "Puerta de entrada",
    "plot_status_state_open": "&aAbierta",
    "plot_status_state_closed": "&cCerrada",
    "plot_status_label_containers": "Contenedores",
    "plot_status_label_redstone_doors": "Redstone y puertas",
    "plot_status_label_vehicles": "Vehículos",
    "plot_status_section_perks": "&7Ventajas y servicios:",
    "plot_status_label_shop_interact": "Interactuar con tiendas",
    "plot_status_state_active": "&aActivado",
    "plot_status_state_inactive": "&7Inactivo",
    "plot_status_label_flight": "Vuelo dentro de esta parcela",
    "plot_status_state_protected": "&aProtegido",
    "plot_status_state_vulnerable": "&cVulnerable",
    "plot_status_line_bullet": "&f- {LABEL}: {STATE}",
    "plot_status_blessing_effect_format": "{COLOR}✦ &f{EFFECT} &7(Efecto &f{TIER}&7)",
    "plot_status_blessing_member_slots_format": "&a✦ &fEspacios de miembros de confianza: &b+{AMOUNT}",
    "plot_status_blessing_generic_format": "&a✦ &f{TEXT}",
}

PACKS["portuguese_br"] = {
    "plot_status_gui_title": "&b✦ Status da parcela",
    "plot_status_header_title": "&b✦ Status da parcela",
    "plot_status_lore": [
        "&7Resumo desta parcela: dono, proteções,",
        "&7bênçãos, crescimento, ClaimBlocks e acesso.",
        " ",
        "&eClique para abrir.",
    ],
    "plot_status_button_lore": [
        "&7Resumo desta parcela: dono, proteções,",
        "&7bênçãos, crescimento, ClaimBlocks e acesso.",
        " ",
        "&eClique para abrir.",
    ],
    "plot_status_kind_personal": "&aParcela pessoal",
    "plot_status_kind_server": "&bParcela de servidor / spawn",
    "plot_status_owner_line": "&7Dono: &f{OWNER}",
    "plot_status_world_line": "&7Mundo: &f{WORLD}",
    "plot_status_level_line": "&7Nível da parcela: &b{LEVEL}&7 / &f{MAX}",
    "plot_status_name_line": "&7Nome: &f{NAME}",
    "plot_status_protection_title": "&cProteções e riscos",
    "plot_status_blessings_title": "&dBênçãos ativas",
    "plot_status_blessings_header_line": "&7Bênçãos ativas:",
    "plot_status_blessings_none_line": "&8- Nenhuma desbloqueada ainda.",
    "plot_status_blessings_footer_line": "&8Só o nível mais alto de cada bênção é mostrado.",
    "plot_status_territory_title": "&aTerritório e crescimento",
    "plot_status_menu_name": "&3✦ Menu AegisGuard",
    "plot_status_territory_rules_line": "&7Regras de território:",
    "plot_status_territory_hint_line": "&b{MENU} &7→ &b{EXPAND}",
    "plot_status_access_title": "&eResumo de acesso",
    "plot_status_members_line": "&7Membros: &f{COUNT}",
    "plot_status_guests_line": "&7Passes de convidado: &f{COUNT}",
    "plot_status_lockdown_on": "&cLockdown: &fAtivo",
    "plot_status_lockdown_off": "&7Lockdown: &fDesligado",
    "plot_status_access_hint": [
        "&8Abra Cargos, Passes de convidado ou Lockdown",
        "&8no menu principal para alterar isto.",
    ],
    "plot_status_upkeep_click": "&eClique para pagar adiantado.",
    "plot_status_section_overview_name": "&bVisão geral",
    "plot_status_section_overview_lore": [
        "&7Um resumo desta parcela: proteções,",
        "&7bênçãos, crescimento e ClaimBlocks.",
    ],
    "plot_status_section_actions_name": "&6Ações do dono",
    "plot_status_section_actions_lore": [
        "&7Unir, transferir, presentear ClaimBlocks",
        "&7ou pagar a manutenção adiantado.",
    ],
    "plot_status_section_combat": "&7Combate e hostis:",
    "plot_status_label_pvp": "PvP",
    "plot_status_label_hostile_mobs": "Mobs hostis",
    "plot_status_label_animals_pets": "Animais e pets",
    "plot_status_section_environment": "&7Ambiente e acesso:",
    "plot_status_label_safe_zone": "Zona segura",
    "plot_status_state_enabled": "&aAtivado",
    "plot_status_state_disabled": "&7Desativado",
    "plot_status_label_entry_gate": "Portão de entrada",
    "plot_status_state_open": "&aAberto",
    "plot_status_state_closed": "&cFechado",
    "plot_status_label_containers": "Contêineres",
    "plot_status_label_redstone_doors": "Redstone e portas",
    "plot_status_label_vehicles": "Veículos",
    "plot_status_section_perks": "&7Vantagens e serviços:",
    "plot_status_label_shop_interact": "Interagir com lojas",
    "plot_status_state_active": "&aAtivado",
    "plot_status_state_inactive": "&7Inativo",
    "plot_status_label_flight": "Voo dentro desta parcela",
    "plot_status_state_protected": "&aProtegido",
    "plot_status_state_vulnerable": "&cVulnerável",
    "plot_status_line_bullet": "&f- {LABEL}: {STATE}",
    "plot_status_blessing_effect_format": "{COLOR}✦ &f{EFFECT} &7(Efeito &f{TIER}&7)",
    "plot_status_blessing_member_slots_format": "&a✦ &fVagas de membros confiáveis: &b+{AMOUNT}",
    "plot_status_blessing_generic_format": "&a✦ &f{TEXT}",
}

PACKS["french_fr"] = {
    "plot_status_gui_title": "&b✦ Statut de la claim",
    "plot_status_header_title": "&b✦ Statut de la claim",
    "plot_status_lore": [
        "&7Aperçu de cette claim : propriétaire, protections,",
        "&7bénédictions, croissance, ClaimBlocks et accès.",
        " ",
        "&eCliquez pour ouvrir.",
    ],
    "plot_status_button_lore": [
        "&7Aperçu de cette claim : propriétaire, protections,",
        "&7bénédictions, croissance, ClaimBlocks et accès.",
        " ",
        "&eCliquez pour ouvrir.",
    ],
    "plot_status_kind_personal": "&aClaim personnelle",
    "plot_status_kind_server": "&bClaim serveur / spawn",
    "plot_status_owner_line": "&7Propriétaire : &f{OWNER}",
    "plot_status_world_line": "&7Monde : &f{WORLD}",
    "plot_status_level_line": "&7Niveau de claim : &b{LEVEL}&7 / &f{MAX}",
    "plot_status_name_line": "&7Nom : &f{NAME}",
    "plot_status_protection_title": "&cProtections et risques",
    "plot_status_blessings_title": "&dBénédictions actives",
    "plot_status_blessings_header_line": "&7Bénédictions actives :",
    "plot_status_blessings_none_line": "&8- Aucune débloquée pour le moment.",
    "plot_status_blessings_footer_line": "&8Seul le palier le plus élevé de chaque bénédiction est affiché.",
    "plot_status_territory_title": "&aTerritoire et croissance",
    "plot_status_menu_name": "&3✦ Menu AegisGuard",
    "plot_status_territory_rules_line": "&7Règles du territoire :",
    "plot_status_territory_hint_line": "&b{MENU} &7→ &b{EXPAND}",
    "plot_status_access_title": "&eAperçu des accès",
    "plot_status_members_line": "&7Membres : &f{COUNT}",
    "plot_status_guests_line": "&7Passes invités : &f{COUNT}",
    "plot_status_lockdown_on": "&cLockdown : &fActif",
    "plot_status_lockdown_off": "&7Lockdown : &fDésactivé",
    "plot_status_access_hint": [
        "&8Ouvrez Rôles, Passes invités ou Lockdown",
        "&8depuis le menu principal pour modifier ceci.",
    ],
    "plot_status_upkeep_click": "&eCliquez pour payer en avance.",
    "plot_status_section_overview_name": "&bAperçu",
    "plot_status_section_overview_lore": [
        "&7Un aperçu de cette claim : protections,",
        "&7bénédictions, croissance et ClaimBlocks.",
    ],
    "plot_status_section_actions_name": "&6Actions du propriétaire",
    "plot_status_section_actions_lore": [
        "&7Fusionner, transférer, offrir des ClaimBlocks",
        "&7ou payer l'entretien en avance.",
    ],
    "plot_status_section_combat": "&7Combat et hostiles :",
    "plot_status_label_pvp": "PvP",
    "plot_status_label_hostile_mobs": "Mobs hostiles",
    "plot_status_label_animals_pets": "Animaux et familiers",
    "plot_status_section_environment": "&7Environnement et accès :",
    "plot_status_label_safe_zone": "Zone sûre",
    "plot_status_state_enabled": "&aActivé",
    "plot_status_state_disabled": "&7Désactivé",
    "plot_status_label_entry_gate": "Barrière d'entrée",
    "plot_status_state_open": "&aOuverte",
    "plot_status_state_closed": "&cFermée",
    "plot_status_label_containers": "Conteneurs",
    "plot_status_label_redstone_doors": "Redstone et portes",
    "plot_status_label_vehicles": "Véhicules",
    "plot_status_section_perks": "&7Avantages et services :",
    "plot_status_label_shop_interact": "Interaction boutique",
    "plot_status_state_active": "&aActivé",
    "plot_status_state_inactive": "&7Inactif",
    "plot_status_label_flight": "Vol dans cette claim",
    "plot_status_state_protected": "&aProtégé",
    "plot_status_state_vulnerable": "&cVulnérable",
    "plot_status_line_bullet": "&f- {LABEL}: {STATE}",
    "plot_status_blessing_effect_format": "{COLOR}✦ &f{EFFECT} &7(Effet &f{TIER}&7)",
    "plot_status_blessing_member_slots_format": "&a✦ &fEmplacements de membres de confiance : &b+{AMOUNT}",
    "plot_status_blessing_generic_format": "&a✦ &f{TEXT}",
}

PACKS["italian_it"] = {
    "plot_status_gui_title": "&b✦ Stato del claim",
    "plot_status_header_title": "&b✦ Stato del claim",
    "plot_status_lore": [
        "&7Riepilogo di questo claim: proprietario, protezioni,",
        "&7benedizioni, crescita, ClaimBlocks e accessi.",
        " ",
        "&eClicca per aprire.",
    ],
    "plot_status_button_lore": [
        "&7Riepilogo di questo claim: proprietario, protezioni,",
        "&7benedizioni, crescita, ClaimBlocks e accessi.",
        " ",
        "&eClicca per aprire.",
    ],
    "plot_status_kind_personal": "&aClaim personale",
    "plot_status_kind_server": "&bClaim server / spawn",
    "plot_status_owner_line": "&7Proprietario: &f{OWNER}",
    "plot_status_world_line": "&7Mondo: &f{WORLD}",
    "plot_status_level_line": "&7Livello del claim: &b{LEVEL}&7 / &f{MAX}",
    "plot_status_name_line": "&7Nome: &f{NAME}",
    "plot_status_protection_title": "&cProtezioni e rischi",
    "plot_status_blessings_title": "&dBenedizioni attive",
    "plot_status_blessings_header_line": "&7Benedizioni attive:",
    "plot_status_blessings_none_line": "&8- Nessuna sbloccata ancora.",
    "plot_status_blessings_footer_line": "&8Viene mostrato solo il livello più alto di ogni benedizione.",
    "plot_status_territory_title": "&aTerritorio e crescita",
    "plot_status_menu_name": "&3✦ Menù AegisGuard",
    "plot_status_territory_rules_line": "&7Regole del territorio:",
    "plot_status_territory_hint_line": "&b{MENU} &7→ &b{EXPAND}",
    "plot_status_access_title": "&eRiepilogo accessi",
    "plot_status_members_line": "&7Membri: &f{COUNT}",
    "plot_status_guests_line": "&7Pass ospite: &f{COUNT}",
    "plot_status_lockdown_on": "&cLockdown: &fAttivo",
    "plot_status_lockdown_off": "&7Lockdown: &fDisattivo",
    "plot_status_access_hint": [
        "&8Apri Ruoli, Pass ospite o Lockdown",
        "&8dal menu principale per cambiarlo.",
    ],
    "plot_status_upkeep_click": "&eClicca per pagare in anticipo.",
    "plot_status_section_overview_name": "&bPanoramica",
    "plot_status_section_overview_lore": [
        "&7Uno sguardo a questo claim: protezioni,",
        "&7benedizioni, crescita e ClaimBlocks.",
    ],
    "plot_status_section_actions_name": "&6Azioni del proprietario",
    "plot_status_section_actions_lore": [
        "&7Unisci, trasferisci, regala ClaimBlocks",
        "&7o paga la manutenzione in anticipo.",
    ],
    "plot_status_section_combat": "&7Combattimento e ostili:",
    "plot_status_label_pvp": "PvP",
    "plot_status_label_hostile_mobs": "Mob ostili",
    "plot_status_label_animals_pets": "Animali e pet",
    "plot_status_section_environment": "&7Ambiente e accesso:",
    "plot_status_label_safe_zone": "Zona sicura",
    "plot_status_state_enabled": "&aAttivo",
    "plot_status_state_disabled": "&7Disattivo",
    "plot_status_label_entry_gate": "Cancello d'ingresso",
    "plot_status_state_open": "&aAperto",
    "plot_status_state_closed": "&cChiuso",
    "plot_status_label_containers": "Contenitori",
    "plot_status_label_redstone_doors": "Redstone e porte",
    "plot_status_label_vehicles": "Veicoli",
    "plot_status_section_perks": "&7Vantaggi e servizi:",
    "plot_status_label_shop_interact": "Interazione negozio",
    "plot_status_state_active": "&aAttivo",
    "plot_status_state_inactive": "&7Inattivo",
    "plot_status_label_flight": "Volo in questo claim",
    "plot_status_state_protected": "&aProtetto",
    "plot_status_state_vulnerable": "&cVulnerabile",
    "plot_status_line_bullet": "&f- {LABEL}: {STATE}",
    "plot_status_blessing_effect_format": "{COLOR}✦ &f{EFFECT} &7(Effetto &f{TIER}&7)",
    "plot_status_blessing_member_slots_format": "&a✦ &fSlot membri fidati: &b+{AMOUNT}",
    "plot_status_blessing_generic_format": "&a✦ &f{TEXT}",
}

PACKS["german_de"] = {
    "plot_status_gui_title": "&b✦ Anspruchsstatus",
    "plot_status_header_title": "&b✦ Anspruchsstatus",
    "plot_status_lore": [
        "&7Überblick über dieses Grundstück: Besitzer, Schutz,",
        "&7Segen, Wachstum, ClaimBlocks und Zugang.",
        " ",
        "&eKlicken zum Öffnen.",
    ],
    "plot_status_button_lore": [
        "&7Überblick über dieses Grundstück: Besitzer, Schutz,",
        "&7Segen, Wachstum, ClaimBlocks und Zugang.",
        " ",
        "&eKlicken zum Öffnen.",
    ],
    "plot_status_kind_personal": "&aPersönliches Grundstück",
    "plot_status_kind_server": "&bServer- / Spawn-Grundstück",
    "plot_status_owner_line": "&7Besitzer: &f{OWNER}",
    "plot_status_world_line": "&7Welt: &f{WORLD}",
    "plot_status_level_line": "&7Grundstücksstufe: &b{LEVEL}&7 / &f{MAX}",
    "plot_status_name_line": "&7Name: &f{NAME}",
    "plot_status_protection_title": "&cSchutz und Risiken",
    "plot_status_blessings_title": "&dAktive Segen",
    "plot_status_blessings_header_line": "&7Aktive Segen:",
    "plot_status_blessings_none_line": "&8- Noch keine freigeschaltet.",
    "plot_status_blessings_footer_line": "&8Es wird nur die höchste Stufe jedes Segens angezeigt.",
    "plot_status_territory_title": "&aGebiet und Wachstum",
    "plot_status_menu_name": "&3✦ AegisGuard-Menü",
    "plot_status_territory_rules_line": "&7Gebietsregeln:",
    "plot_status_territory_hint_line": "&b{MENU} &7→ &b{EXPAND}",
    "plot_status_access_title": "&eZugangsüberblick",
    "plot_status_members_line": "&7Mitglieder: &f{COUNT}",
    "plot_status_guests_line": "&7Gästepässe: &f{COUNT}",
    "plot_status_lockdown_on": "&cLockdown: &fAktiv",
    "plot_status_lockdown_off": "&7Lockdown: &fAus",
    "plot_status_access_hint": [
        "&8Öffne Rollen, Gästepässe oder Lockdown",
        "&8im Hauptmenü, um dies zu ändern.",
    ],
    "plot_status_upkeep_click": "&eKlicken, um früh zu zahlen.",
    "plot_status_section_overview_name": "&bÜberblick",
    "plot_status_section_overview_lore": [
        "&7Ein Überblick über dieses Grundstück: Schutz,",
        "&7Segen, Wachstum und ClaimBlocks.",
    ],
    "plot_status_section_actions_name": "&6Besitzeraktionen",
    "plot_status_section_actions_lore": [
        "&7Zusammenführen, übertragen, ClaimBlocks schenken",
        "&7oder Unterhalt früh zahlen.",
    ],
    "plot_status_section_combat": "&7Kampf und Feinde:",
    "plot_status_label_pvp": "PvP",
    "plot_status_label_hostile_mobs": "Feindliche Mobs",
    "plot_status_label_animals_pets": "Tiere und Haustiere",
    "plot_status_section_environment": "&7Umgebung und Zugang:",
    "plot_status_label_safe_zone": "Schutzzone",
    "plot_status_state_enabled": "&aAktiviert",
    "plot_status_state_disabled": "&7Deaktiviert",
    "plot_status_label_entry_gate": "Eingangstor",
    "plot_status_state_open": "&aOffen",
    "plot_status_state_closed": "&cGeschlossen",
    "plot_status_label_containers": "Behälter",
    "plot_status_label_redstone_doors": "Redstone und Türen",
    "plot_status_label_vehicles": "Fahrzeuge",
    "plot_status_section_perks": "&7Vorteile und Dienste:",
    "plot_status_label_shop_interact": "Marktinteraktion",
    "plot_status_state_active": "&aAktiviert",
    "plot_status_state_inactive": "&7Inaktiv",
    "plot_status_label_flight": "Flug auf diesem Grundstück",
    "plot_status_state_protected": "&aGeschützt",
    "plot_status_state_vulnerable": "&cUngeschützt",
    "plot_status_line_bullet": "&f- {LABEL}: {STATE}",
    "plot_status_blessing_effect_format": "{COLOR}✦ &f{EFFECT} &7(Effekt &f{TIER}&7)",
    "plot_status_blessing_member_slots_format": "&a✦ &fVertrauenswürdige Mitgliederplätze: &b+{AMOUNT}",
    "plot_status_blessing_generic_format": "&a✦ &f{TEXT}",
}

PACKS["polish_pl"] = {
    "plot_status_gui_title": "&b✦ Status działki",
    "plot_status_header_title": "&b✦ Status działki",
    "plot_status_lore": [
        "&7Podgląd tej działki: właściciel, ochrony,",
        "&7błogosławieństwa, rozwój, ClaimBlocks i dostęp.",
        " ",
        "&eKliknij, aby otworzyć.",
    ],
    "plot_status_button_lore": [
        "&7Podgląd tej działki: właściciel, ochrony,",
        "&7błogosławieństwa, rozwój, ClaimBlocks i dostęp.",
        " ",
        "&eKliknij, aby otworzyć.",
    ],
    "plot_status_kind_personal": "&aDziałka osobista",
    "plot_status_kind_server": "&bDziałka serwera / spawnu",
    "plot_status_owner_line": "&7Właściciel: &f{OWNER}",
    "plot_status_world_line": "&7Świat: &f{WORLD}",
    "plot_status_level_line": "&7Poziom działki: &b{LEVEL}&7 / &f{MAX}",
    "plot_status_name_line": "&7Nazwa: &f{NAME}",
    "plot_status_protection_title": "&cOchrony i zagrożenia",
    "plot_status_blessings_title": "&dAktywne błogosławieństwa",
    "plot_status_blessings_header_line": "&7Aktywne błogosławieństwa:",
    "plot_status_blessings_none_line": "&8- Jeszcze żadnych nie odblokowano.",
    "plot_status_blessings_footer_line": "&8Pokazywany jest tylko najwyższy poziom każdego błogosławieństwa.",
    "plot_status_territory_title": "&aTerytorium i rozwój",
    "plot_status_menu_name": "&3✦ Menu AegisGuard",
    "plot_status_territory_rules_line": "&7Zasady terytorium:",
    "plot_status_territory_hint_line": "&b{MENU} &7→ &b{EXPAND}",
    "plot_status_access_title": "&ePodgląd dostępu",
    "plot_status_members_line": "&7Członkowie: &f{COUNT}",
    "plot_status_guests_line": "&7Przepustki gości: &f{COUNT}",
    "plot_status_lockdown_on": "&cLockdown: &fAktywny",
    "plot_status_lockdown_off": "&7Lockdown: &fWyłączony",
    "plot_status_access_hint": [
        "&8Otwórz Role, Przepustki gości lub Lockdown",
        "&8w menu głównym, aby to zmienić.",
    ],
    "plot_status_upkeep_click": "&eKliknij, aby zapłacić wcześniej.",
    "plot_status_section_overview_name": "&bPrzegląd",
    "plot_status_section_overview_lore": [
        "&7Podgląd tej działki: ochrony,",
        "&7błogosławieństwa, rozwój i ClaimBlocks.",
    ],
    "plot_status_section_actions_name": "&6Akcje właściciela",
    "plot_status_section_actions_lore": [
        "&7Scal, przenieś, podaruj ClaimBlocks",
        "&7albo zapłać utrzymanie wcześniej.",
    ],
    "plot_status_section_combat": "&7Walka i wrogowie:",
    "plot_status_label_pvp": "PvP",
    "plot_status_label_hostile_mobs": "Wrogie moby",
    "plot_status_label_animals_pets": "Zwierzęta i pupile",
    "plot_status_section_environment": "&7Otoczenie i dostęp:",
    "plot_status_label_safe_zone": "Strefa bezpieczna",
    "plot_status_state_enabled": "&aWłączone",
    "plot_status_state_disabled": "&7Wyłączone",
    "plot_status_label_entry_gate": "Brama wejścia",
    "plot_status_state_open": "&aOtwarta",
    "plot_status_state_closed": "&cZamknięta",
    "plot_status_label_containers": "Pojemniki",
    "plot_status_label_redstone_doors": "Redstone i drzwi",
    "plot_status_label_vehicles": "Pojazdy",
    "plot_status_section_perks": "&7Korzyści i usługi:",
    "plot_status_label_shop_interact": "Interakcja ze sklepem",
    "plot_status_state_active": "&aWłączone",
    "plot_status_state_inactive": "&7Nieaktywne",
    "plot_status_label_flight": "Lot na tej działce",
    "plot_status_state_protected": "&aChronione",
    "plot_status_state_vulnerable": "&cNarażone",
    "plot_status_line_bullet": "&f- {LABEL}: {STATE}",
    "plot_status_blessing_effect_format": "{COLOR}✦ &f{EFFECT} &7(Efekt &f{TIER}&7)",
    "plot_status_blessing_member_slots_format": "&a✦ &fMiejsca zaufanych członków: &b+{AMOUNT}",
    "plot_status_blessing_generic_format": "&a✦ &f{TEXT}",
}

MARKER = "# --- 1.3.0 claim status menu polish ---"

def render_block(keys):
    lines = ["", MARKER]
    for key, value in keys.items():
        if isinstance(value, list):
            lines.append(f"{key}:")
            lines.append(dump(value))
        else:
            lines.append(f"{key}: {dump(value)}")
    lines.append("")
    return "\n".join(lines)

def upsert(path: Path, keys: dict):
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    if MARKER in text:
        text = text.split(MARKER)[0].rstrip() + "\n"
    path.write_text(text.rstrip() + "\n" + render_block(keys), encoding="utf-8")

def main():
    english_keys = PACKS["modern_english"].keys()
    for lang in LANGS:
        keys = PACKS[lang]
        missing = [k for k in english_keys if k not in keys]
        extra = [k for k in keys if k not in english_keys]
        if missing or extra:
            raise SystemExit(f"{lang} missing={missing} extra={extra}")
        upsert(ROOT / "lang" / lang / "guis.yml", keys)
        upsert(ROOT / "codex" / f"{lang}.yml", keys)
        print(f"updated {lang}")

if __name__ == "__main__":
    main()
