#!/usr/bin/env python3
"""Manual translations for hardcoded-string localization keys."""

MANUAL: dict[str, dict[str, str]] = {
    "spanish_mx": {
        "&aAegisGuard reload complete.": "&aRecarga de AegisGuard completa.",
        "&6Bypass Mode: {STATE}": "&6Modo bypass: {STATE}",
        "&cThe audit ledger is unavailable.": "&cEl registro de auditoría no está disponible.",
        "&eYou already have an Aegis claim wand or Sentinel's Scepter.": "&eYa tienes una varita de claim de Aegis o el Cetro del Centinela.",
        "&aYou received the Sentinel's Scepter.": "&aRecibiste el Cetro del Centinela.",
        "&7Select two corners, then use &b/agadmin claim&7.": "&7Selecciona dos esquinas y usa &b/agadmin claim&7.",
        "&cMigration wand is unavailable.": "&cLa varita de migración no está disponible.",
        "&eUsage: /aegisadmin wand <server|migration>": "&eUso: /aegisadmin wand <server|migration>",
        "&cYou need to select two corners first with the Sentinel's Scepter.": "&cPrimero debes seleccionar dos esquinas con el Cetro del Centinela.",
        "&7Use &b/agadmin wand server &7to get it.": "&7Usa &b/agadmin wand server &7para obtenerlo.",
        "&cStand inside the server zone you want to manage.": "&cPárate dentro de la zona del servidor que quieres administrar.",
        "&7A tool of absolute authority.": "&7Una herramienta de autoridad absoluta.",
        "&eRight-Click: &fSelect Pos 1": "&eClic derecho: &fSeleccionar Pos 1",
        "&eLeft-Click: &fSelect Pos 2": "&eClic izquierdo: &fSeleccionar Pos 2",
        "&cCreates server zones directly.": "&cCrea zonas del servidor directamente.",
        "&eNo supported migration sources were detected.": "&eNo se detectaron fuentes de migración compatibles.",
        "&6Detected migration sources:": "&6Fuentes de migración detectadas:",
        "&7 - {SOURCE}": "&7 - {SOURCE}",
        "&eUsage: /agadmin migrate <preview|import> <source>": "&eUso: /agadmin migrate <preview|import> <source>",
        "&cUnknown source. Use griefprevention/gp, griefdefender/gd, or lands.": "&cFuente desconocida. Usa griefprevention/gp, griefdefender/gd o lands.",
        "&cMigration preview failed: {ERROR}": "&cFalló la vista previa de migración: {ERROR}",
        "&cMigration failed: {ERROR}": "&cFalló la migración: {ERROR}",
        "&eUnknown migrate action. Use list, preview, import, or help.": "&eAcción de migración desconocida. Usa list, preview, import o help.",
        "&cStand inside a plot to create a recovery snapshot.": "&cPárate dentro de un terreno para crear una instantánea de recuperación.",
        "&cYou cannot create a recovery snapshot for this plot.": "&cNo puedes crear una instantánea de recuperación para este terreno.",
        "&aCreated recovery snapshot: {ID}": "&aInstantánea de recuperación creada: {ID}",
        "Manual admin recovery snapshot by {PLAYER}": "Instantánea de recuperación manual de admin por {PLAYER}",
        "No reason recorded": "Sin motivo registrado",
        "&eUsage: /agadmin blocks <get|add|remove|set> <player> [amount] [reason]": "&eUso: /agadmin blocks <get|add|remove|set> <player> [amount] [reason]",
        "&eUsage: /agadmin blocks <add|remove|set> <player> <amount> [reason]": "&eUso: /agadmin blocks <add|remove|set> <player> <amount> [reason]",
        "&6{PLAYER} &7ClaimBlocks: total={TOTAL}, used={USED}, available={AVAILABLE}": "&6{PLAYER} &7ClaimBlocks: total={TOTAL}, usados={USED}, disponibles={AVAILABLE}",
        "&cAmount must be a whole number.": "&cLa cantidad debe ser un número entero.",
        "&cAmount must be between 0 and {MAX}.": "&cLa cantidad debe estar entre 0 y {MAX}.",
        "&aUpdated {PLAYER} to {AMOUNT} available ClaimBlocks.": "&aActualizaste a {PLAYER} a {AMOUNT} ClaimBlocks disponibles.",
        "No reason supplied": "Sin motivo indicado",
        "&eUsage: /agadmin merge <north|south|east|west> confirm": "&eUso: /agadmin merge <north|south|east|west> confirm",
        "&cDirection must be north, south, east, or west.": "&cLa dirección debe ser north, south, east o west.",
        "&cStand inside the server zone that should remain after the merge.": "&cPárate dentro de la zona del servidor que debe permanecer tras la fusión.",
        "&cNo perfectly aligned adjacent server zone exists in that direction.": "&cNo hay una zona del servidor adyacente perfectamente alineada en esa dirección.",
        "&cMarket or rental state must be cleared before merging server zones.": "&cDebes limpiar el estado de mercado o alquiler antes de fusionar zonas del servidor.",
        "&aServer zones merged. Recovery snapshots were created.": "&aZonas del servidor fusionadas. Se crearon instantáneas de recuperación.",
        "&cMerge failed and was rolled back: {ERROR}": "&cLa fusión falló y se revirtió: {ERROR}",
        "&aDelivered {SETTLED} pending settlement(s). Remaining: {REMAINING}": "&aEntregados {SETTLED} pago(s) pendiente(s). Restantes: {REMAINING}",
        "&eUsage: /agadmin rentals cancel <plot-id> confirm": "&eUso: /agadmin rentals cancel <plot-id> confirm",
        "&7Or: /agadmin rentals retry-settlements": "&7O: /agadmin rentals retry-settlements",
        "&cStand inside the rented plot or provide its UUID.": "&cPárate dentro del terreno alquilado o proporciona su UUID.",
        "&cPlot ID must be a valid UUID, or use 'here'.": "&cEl ID del terreno debe ser un UUID válido, o usa 'here'.",
        "&cNo active rental contract exists for that plot.": "&cNo hay un contrato de alquiler activo para ese terreno.",
        "&aRental contract cancelled safely.": "&aContrato de alquiler cancelado de forma segura.",
        "&eAn administrator ended rental contract &f{PLOT}&e.": "&eUn administrador terminó el contrato de alquiler &f{PLOT}&e.",
        "&eAn administrator ended rental contract &f{PLOT}&e. Your deposit was refunded or queued.": "&eUn administrador terminó el contrato de alquiler &f{PLOT}&e. Tu depósito fue reembolsado o puesto en cola.",
        "&cStand inside the plot you want to update.": "&cPárate dentro del terreno que quieres actualizar.",
        "&eUsage: /agadmin discover <feature|unfeature|show|hide>": "&eUso: /agadmin discover <feature|unfeature|show|hide>",
        "&aDiscovery state updated: {ACTION}.": "&aEstado de descubrimiento actualizado: {ACTION}.",
        "&cStand inside a plot to view its activity.": "&cPárate dentro de un terreno para ver su actividad.",
        "&6Territory Activity: {PLOT}": "&6Actividad del territorio: {PLOT}",
        "&7No activity recorded.": "&7No hay actividad registrada.",
        "&8- &e{TYPE} &7{DETAILS}": "&8- &e{TYPE} &7{DETAILS}",
        "&6[Admin] &e{PLAYER} &7reloaded AegisGuard.": "&6[Admin] &e{PLAYER} &7recargó AegisGuard.",
        "&6[Admin] &e{PLAYER} &7set bypass mode to {STATE}&7.": "&6[Admin] &e{PLAYER} &7cambió el modo bypass a {STATE}&7.",
        "&6[Admin] &e{PLAYER} &7{ACTION}.": "&6[Admin] &e{PLAYER} &7{ACTION}.",
        "&6[Admin] &e{PLAYER} &7converted plot {PLOT} into a server zone.": "&6[Admin] &e{PLAYER} &7convirtió el terreno {PLOT} en una zona del servidor.",
        "&6Admin Update": "&6Actualización de admin",
        "&aFirst corner selected: &f{X}, {Y}, {Z}": "&aPrimera esquina seleccionada: &f{X}, {Y}, {Z}",
        "&bSecond corner selected: &f{X}, {Y}, {Z}": "&bSegunda esquina seleccionada: &f{X}, {Y}, {Z}",
        "&7Selection area: &e{AREA} blocks &7- use &a{COMMAND} &7to confirm.": "&7Área de selección: &e{AREA} bloques &7- usa &a{COMMAND} &7para confirmar.",
        "&cEnter a valid Minecraft player name.": "&cIngresa un nombre de jugador de Minecraft válido.",
        "&cThat player has not played on this server.": "&cEse jugador no ha jugado en este servidor.",
        "&cThat player cannot receive a pass for this plot.": "&cEse jugador no puede recibir un pase para este terreno.",
        "&6&lAegisGuard Staff Health Check": "&6&lChequeo de salud del staff de AegisGuard",
        "{COLOR}[{CODE}] &7{MESSAGE}": "{COLOR}[{CODE}] &7{MESSAGE}",
        "Plot data store is not available.": "El almacén de terrenos no está disponible.",
        "{COUNT} plot(s) reference worlds that are not loaded.": "{COUNT} terreno(s) referencian mundos que no están cargados.",
        "{COUNT} warp/spawn destination(s) are missing or unsafe.": "{COUNT} destino(s) de warp/spawn faltan o no son seguros.",
        "{COUNT} expired Guest Pass(es) still stored on plots.": "{COUNT} Guest Pass(es) vencido(s) aún guardados en terrenos.",
        "Snapshot manager is disabled or missing.": "El administrador de instantáneas está desactivado o ausente.",
        "Snapshots stored: {COUNT} (auto lockdown={LOCKDOWN}, alliance={ALLIANCE}).": "Instantáneas guardadas: {COUNT} (auto lockdown={LOCKDOWN}, alliance={ALLIANCE}).",
        "Safe Travel gate is disabled in config.": "La puerta de Viaje Seguro está desactivada en la config.",
        "config_schema is behind CURRENT_SCHEMA {SCHEMA}.": "config_schema está detrás de CURRENT_SCHEMA {SCHEMA}.",
        "Mob barrier enabled={ENABLED}, hostile={HOSTILE}, passive={PASSIVE}, boss={BOSS}.": "Barrera de mobs enabled={ENABLED}, hostile={HOSTILE}, passive={PASSIVE}, boss={BOSS}.",
        "No staff health issues detected.": "No se detectaron problemas de salud del staff.",
        "&eYour rental expires in less than {HOURS} hour(s). Use &b/ag rental renew&e.": "&eTu alquiler vence en menos de {HOURS} hora(s). Usa &b/ag rental renew&e.",
        "&eA plot rental expires soon. Plot: &f{PLOT}": "&eUn alquiler de terreno vence pronto. Terreno: &f{PLOT}",
        "&cAuto-renew failed: insufficient funds. Your rental expires soon.": "&cFalló la renovación automática: fondos insuficientes. Tu alquiler vence pronto.",
        "&cAuto-renew payment failed. No time was added.": "&cFalló el pago de renovación automática. No se añadió tiempo.",
        "&aRental auto-renewed for &e{DAYS} day(s)&a.": "&aAlquiler renovado automáticamente por &e{DAYS} día(s)&a.",
        "&aA rental contract auto-renewed for &e{DAYS} day(s)&a.": "&aUn contrato de alquiler se renovó automáticamente por &e{DAYS} día(s)&a.",
        "&aRental deposit refunded: &6{AMOUNT}&a.": "&aDepósito de alquiler reembolsado: &6{AMOUNT}&a.",
        "&aYour plot was rented by &f{PLAYER}&a for &e{DAYS} day(s)&a.": "&aTu terreno fue alquilado por &f{PLAYER}&a durante &e{DAYS} día(s)&a.",
        "&aA rental contract was renewed for &e{DAYS} day(s)&a.": "&aUn contrato de alquiler se renovó por &e{DAYS} día(s)&a.",
        "&8[&bAegisGuard&8] &7Notification Settings:": "&8[&bAegisGuard&8] &7Ajustes de notificaciones:",
        " &7- Plot Greetings: {STATE}": " &7- Saludos de terreno: {STATE}",
        " &7- Admin Updates: {STATE}": " &7- Actualizaciones de admin: {STATE}",
        " &7- Mode: &b{MODE}": " &7- Modo: &b{MODE}",
        "&aEnabled": "&aActivado",
        "&cDisabled": "&cDesactivado",
        "Server Warp": "Warp del servidor",
        "Category: {CATEGORY}": "Categoría: {CATEGORY}",
        "&7Likes: &d{LIKES} &8| &7Visits: &b{VISITS}": "&7Me gusta: &d{LIKES} &8| &7Visitas: &b{VISITS}",
        "&6★ Featured Territory": "&6★ Territorio destacado",
        "&eRight-click to favorite": "&eClic derecho para favorito",
        "&eRight-click to remove favorite": "&eClic derecho para quitar favorito",
        "Unknown": "Desconocido",
        "&aJoin {GROUP}": "&aUnirse a {GROUP}",
        "None": "Ninguno",
    },
}

MANUAL["spanish_ar"] = dict(MANUAL["spanish_mx"])

MANUAL["portuguese_br"] = {
    **{k: v for k, v in {
        "&aAegisGuard reload complete.": "&aRecarga do AegisGuard concluída.",
        "&6Bypass Mode: {STATE}": "&6Modo bypass: {STATE}",
        "&cThe audit ledger is unavailable.": "&cO registro de auditoria está indisponível.",
        "&eYou already have an Aegis claim wand or Sentinel's Scepter.": "&eVocê já tem uma varinha de claim da Aegis ou o Cetro do Sentinela.",
        "&aYou received the Sentinel's Scepter.": "&aVocê recebeu o Cetro do Sentinela.",
        "&7Select two corners, then use &b/agadmin claim&7.": "&7Selecione dois cantos e use &b/agadmin claim&7.",
        "&cMigration wand is unavailable.": "&cA varinha de migração está indisponível.",
        "&cEnter a valid Minecraft player name.": "&cDigite um nome de jogador do Minecraft válido.",
        "&cThat player has not played on this server.": "&cEsse jogador nunca jogou neste servidor.",
        "&cThat player cannot receive a pass for this plot.": "&cEsse jogador não pode receber um passe para este terreno.",
        "&6&lAegisGuard Staff Health Check": "&6&lVerificação de saúde da staff do AegisGuard",
        "&6Admin Update": "&6Atualização da admin",
        "&aEnabled": "&aAtivado",
        "&cDisabled": "&cDesativado",
        "Server Warp": "Warp do servidor",
        "Category: {CATEGORY}": "Categoria: {CATEGORY}",
        "&7Likes: &d{LIKES} &8| &7Visits: &b{VISITS}": "&7Curtidas: &d{LIKES} &8| &7Visitas: &b{VISITS}",
        "&6★ Featured Territory": "&6★ Território em destaque",
        "&eRight-click to favorite": "&eClique direito para favoritar",
        "&eRight-click to remove favorite": "&eClique direito para remover favorito",
        "Unknown": "Desconhecido",
        "&aJoin {GROUP}": "&aEntrar em {GROUP}",
        "None": "Nenhum",
        "No staff health issues detected.": "Nenhum problema de saúde da staff detectado.",
        "&aFirst corner selected: &f{X}, {Y}, {Z}": "&aPrimeiro canto selecionado: &f{X}, {Y}, {Z}",
        "&bSecond corner selected: &f{X}, {Y}, {Z}": "&bSegundo canto selecionado: &f{X}, {Y}, {Z}",
        "&7Selection area: &e{AREA} blocks &7- use &a{COMMAND} &7to confirm.": "&7Área da seleção: &e{AREA} blocos &7- use &a{COMMAND} &7para confirmar.",
        "&eYour rental expires in less than {HOURS} hour(s). Use &b/ag rental renew&e.": "&eSeu aluguel expira em menos de {HOURS} hora(s). Use &b/ag rental renew&e.",
        "&aRental auto-renewed for &e{DAYS} day(s)&a.": "&aAluguel renovado automaticamente por &e{DAYS} dia(s)&a.",
        "&aYour plot was rented by &f{PLAYER}&a for &e{DAYS} day(s)&a.": "&aSeu terreno foi alugado por &f{PLAYER}&a por &e{DAYS} dia(s)&a.",
        "&8[&bAegisGuard&8] &7Notification Settings:": "&8[&bAegisGuard&8] &7Configurações de notificação:",
        " &7- Plot Greetings: {STATE}": " &7- Saudações de terreno: {STATE}",
        " &7- Admin Updates: {STATE}": " &7- Atualizações da admin: {STATE}",
        " &7- Mode: &b{MODE}": " &7- Modo: &b{MODE}",
    }.items()}
}

MANUAL["french_fr"] = {
    "&aAegisGuard reload complete.": "&aRechargement d'AegisGuard terminé.",
    "&6Bypass Mode: {STATE}": "&6Mode bypass : {STATE}",
    "&cThe audit ledger is unavailable.": "&cLe registre d'audit est indisponible.",
    "&eYou already have an Aegis claim wand or Sentinel's Scepter.": "&eVous avez déjà une baguette de claim Aegis ou le Sceptre du Sentinelle.",
    "&aYou received the Sentinel's Scepter.": "&aVous avez reçu le Sceptre du Sentinelle.",
    "&7Select two corners, then use &b/agadmin claim&7.": "&7Sélectionnez deux coins, puis utilisez &b/agadmin claim&7.",
    "&cMigration wand is unavailable.": "&cLa baguette de migration est indisponible.",
    "&cEnter a valid Minecraft player name.": "&cEntrez un nom de joueur Minecraft valide.",
    "&cThat player has not played on this server.": "&cCe joueur n'a jamais joué sur ce serveur.",
    "&cThat player cannot receive a pass for this plot.": "&cCe joueur ne peut pas recevoir de pass pour ce terrain.",
    "&6&lAegisGuard Staff Health Check": "&6&lContrôle de santé du staff AegisGuard",
    "&6Admin Update": "&6Mise à jour admin",
    "&aEnabled": "&aActivé",
    "&cDisabled": "&cDésactivé",
    "Server Warp": "Warp serveur",
    "Category: {CATEGORY}": "Catégorie : {CATEGORY}",
    "&7Likes: &d{LIKES} &8| &7Visits: &b{VISITS}": "&7J'aime : &d{LIKES} &8| &7Visites : &b{VISITS}",
    "&6★ Featured Territory": "&6★ Territoire mis en avant",
    "&eRight-click to favorite": "&eClic droit pour ajouter aux favoris",
    "&eRight-click to remove favorite": "&eClic droit pour retirer des favoris",
    "Unknown": "Inconnu",
    "&aJoin {GROUP}": "&aRejoindre {GROUP}",
    "None": "Aucun",
    "No staff health issues detected.": "Aucun problème de santé du staff détecté.",
    "&aFirst corner selected: &f{X}, {Y}, {Z}": "&aPremier coin sélectionné : &f{X}, {Y}, {Z}",
    "&bSecond corner selected: &f{X}, {Y}, {Z}": "&bSecond coin sélectionné : &f{X}, {Y}, {Z}",
    "&7Selection area: &e{AREA} blocks &7- use &a{COMMAND} &7to confirm.": "&7Zone de sélection : &e{AREA} blocs &7- utilisez &a{COMMAND} &7pour confirmer.",
    "&eYour rental expires in less than {HOURS} hour(s). Use &b/ag rental renew&e.": "&eVotre location expire dans moins de {HOURS} heure(s). Utilisez &b/ag rental renew&e.",
    "&aRental auto-renewed for &e{DAYS} day(s)&a.": "&aLocation renouvelée automatiquement pour &e{DAYS} jour(s)&a.",
    "&aYour plot was rented by &f{PLAYER}&a for &e{DAYS} day(s)&a.": "&aVotre terrain a été loué par &f{PLAYER}&a pour &e{DAYS} jour(s)&a.",
    "&8[&bAegisGuard&8] &7Notification Settings:": "&8[&bAegisGuard&8] &7Paramètres de notification :",
    " &7- Plot Greetings: {STATE}": " &7- Salutations de terrain : {STATE}",
    " &7- Admin Updates: {STATE}": " &7- Mises à jour admin : {STATE}",
    " &7- Mode: &b{MODE}": " &7- Mode : &b{MODE}",
}

MANUAL["italian_it"] = {
    "&aAegisGuard reload complete.": "&aRicarica di AegisGuard completata.",
    "&6Bypass Mode: {STATE}": "&6Modalità bypass: {STATE}",
    "&cThe audit ledger is unavailable.": "&cIl registro di audit non è disponibile.",
    "&eYou already have an Aegis claim wand or Sentinel's Scepter.": "&eHai già una bacchetta claim Aegis o lo Scettro della Sentinella.",
    "&aYou received the Sentinel's Scepter.": "&aHai ricevuto lo Scettro della Sentinella.",
    "&7Select two corners, then use &b/agadmin claim&7.": "&7Seleziona due angoli, poi usa &b/agadmin claim&7.",
    "&cMigration wand is unavailable.": "&cLa bacchetta di migrazione non è disponibile.",
    "&cEnter a valid Minecraft player name.": "&cInserisci un nome giocatore Minecraft valido.",
    "&cThat player has not played on this server.": "&cQuel giocatore non ha mai giocato su questo server.",
    "&cThat player cannot receive a pass for this plot.": "&cQuel giocatore non può ricevere un pass per questo lotto.",
    "&6&lAegisGuard Staff Health Check": "&6&lControllo salute staff AegisGuard",
    "&6Admin Update": "&6Aggiornamento admin",
    "&aEnabled": "&aAttivo",
    "&cDisabled": "&cDisattivo",
    "Server Warp": "Warp del server",
    "Category: {CATEGORY}": "Categoria: {CATEGORY}",
    "&7Likes: &d{LIKES} &8| &7Visits: &b{VISITS}": "&7Mi piace: &d{LIKES} &8| &7Visite: &b{VISITS}",
    "&6★ Featured Territory": "&6★ Territorio in evidenza",
    "&eRight-click to favorite": "&eClick destro per aggiungere ai preferiti",
    "&eRight-click to remove favorite": "&eClick destro per rimuovere dai preferiti",
    "Unknown": "Sconosciuto",
    "&aJoin {GROUP}": "&aUnisciti a {GROUP}",
    "None": "Nessuno",
    "No staff health issues detected.": "Nessun problema di salute dello staff rilevato.",
    "&aFirst corner selected: &f{X}, {Y}, {Z}": "&aPrimo angolo selezionato: &f{X}, {Y}, {Z}",
    "&bSecond corner selected: &f{X}, {Y}, {Z}": "&bSecondo angolo selezionato: &f{X}, {Y}, {Z}",
    "&7Selection area: &e{AREA} blocks &7- use &a{COMMAND} &7to confirm.": "&7Area di selezione: &e{AREA} blocchi &7- usa &a{COMMAND} &7per confermare.",
    "&eYour rental expires in less than {HOURS} hour(s). Use &b/ag rental renew&e.": "&eIl tuo affitto scade tra meno di {HOURS} ora/e. Usa &b/ag rental renew&e.",
    "&aRental auto-renewed for &e{DAYS} day(s)&a.": "&aAffitto rinnovato automaticamente per &e{DAYS} giorno/i&a.",
    "&aYour plot was rented by &f{PLAYER}&a for &e{DAYS} day(s)&a.": "&aIl tuo lotto è stato affittato da &f{PLAYER}&a per &e{DAYS} giorno/i&a.",
    "&8[&bAegisGuard&8] &7Notification Settings:": "&8[&bAegisGuard&8] &7Impostazioni notifiche:",
    " &7- Plot Greetings: {STATE}": " &7- Saluti del lotto: {STATE}",
    " &7- Admin Updates: {STATE}": " &7- Aggiornamenti admin: {STATE}",
    " &7- Mode: &b{MODE}": " &7- Modalità: &b{MODE}",
}

MANUAL["german_de"] = {
    "&aAegisGuard reload complete.": "&aAegisGuard-Neuladen abgeschlossen.",
    "&6Bypass Mode: {STATE}": "&6Bypass-Modus: {STATE}",
    "&cThe audit ledger is unavailable.": "&cDas Audit-Protokoll ist nicht verfügbar.",
    "&eYou already have an Aegis claim wand or Sentinel's Scepter.": "&eDu hast bereits einen Aegis-Claim-Stab oder das Zepter der Wache.",
    "&aYou received the Sentinel's Scepter.": "&aDu hast das Zepter der Wache erhalten.",
    "&7Select two corners, then use &b/agadmin claim&7.": "&7Wähle zwei Ecken, dann nutze &b/agadmin claim&7.",
    "&cMigration wand is unavailable.": "&cDer Migrationsstab ist nicht verfügbar.",
    "&cEnter a valid Minecraft player name.": "&cGib einen gültigen Minecraft-Spielernamen ein.",
    "&cThat player has not played on this server.": "&cDieser Spieler hat auf diesem Server noch nicht gespielt.",
    "&cThat player cannot receive a pass for this plot.": "&cDieser Spieler kann keinen Pass für dieses Grundstück erhalten.",
    "&6&lAegisGuard Staff Health Check": "&6&lAegisGuard Staff-Gesundheitscheck",
    "&6Admin Update": "&6Admin-Update",
    "&aEnabled": "&aAktiviert",
    "&cDisabled": "&cDeaktiviert",
    "Server Warp": "Server-Warp",
    "Category: {CATEGORY}": "Kategorie: {CATEGORY}",
    "&7Likes: &d{LIKES} &8| &7Visits: &b{VISITS}": "&7Likes: &d{LIKES} &8| &7Besuche: &b{VISITS}",
    "&6★ Featured Territory": "&6★ Hervorgehobenes Gebiet",
    "&eRight-click to favorite": "&eRechtsklick zum Favorisieren",
    "&eRight-click to remove favorite": "&eRechtsklick zum Entfernen aus Favoriten",
    "Unknown": "Unbekannt",
    "&aJoin {GROUP}": "&a{GROUP} beitreten",
    "None": "Keine",
    "No staff health issues detected.": "Keine Staff-Gesundheitsprobleme gefunden.",
    "&aFirst corner selected: &f{X}, {Y}, {Z}": "&aErste Ecke gewählt: &f{X}, {Y}, {Z}",
    "&bSecond corner selected: &f{X}, {Y}, {Z}": "&bZweite Ecke gewählt: &f{X}, {Y}, {Z}",
    "&7Selection area: &e{AREA} blocks &7- use &a{COMMAND} &7to confirm.": "&7Auswahlfläche: &e{AREA} Blöcke &7- nutze &a{COMMAND} &7zum Bestätigen.",
    "&eYour rental expires in less than {HOURS} hour(s). Use &b/ag rental renew&e.": "&eDeine Miete endet in weniger als {HOURS} Stunde(n). Nutze &b/ag rental renew&e.",
    "&aRental auto-renewed for &e{DAYS} day(s)&a.": "&aMiete automatisch um &e{DAYS} Tag(e)&a verlängert.",
    "&aYour plot was rented by &f{PLAYER}&a for &e{DAYS} day(s)&a.": "&aDein Grundstück wurde von &f{PLAYER}&a für &e{DAYS} Tag(e)&a gemietet.",
    "&8[&bAegisGuard&8] &7Notification Settings:": "&8[&bAegisGuard&8] &7Benachrichtigungseinstellungen:",
    " &7- Plot Greetings: {STATE}": " &7- Grundstücksbegrüßungen: {STATE}",
    " &7- Admin Updates: {STATE}": " &7- Admin-Updates: {STATE}",
    " &7- Mode: &b{MODE}": " &7- Modus: &b{MODE}",
}

MANUAL["polish_pl"] = {
    "&aAegisGuard reload complete.": "&aPrzeładowanie AegisGuard zakończone.",
    "&6Bypass Mode: {STATE}": "&6Tryb omijania: {STATE}",
    "&cThe audit ledger is unavailable.": "&cDziennik audytu jest niedostępny.",
    "&eYou already have an Aegis claim wand or Sentinel's Scepter.": "&eMasz już różdżkę claim Aegis lub Berło Wartownika.",
    "&aYou received the Sentinel's Scepter.": "&aOtrzymałeś Berło Wartownika.",
    "&7Select two corners, then use &b/agadmin claim&7.": "&7Zaznacz dwa narożniki, potem użyj &b/agadmin claim&7.",
    "&cMigration wand is unavailable.": "&cRóżdżka migracji jest niedostępna.",
    "&cEnter a valid Minecraft player name.": "&cPodaj prawidłową nazwę gracza Minecraft.",
    "&cThat player has not played on this server.": "&cTen gracz nie grał na tym serwerze.",
    "&cThat player cannot receive a pass for this plot.": "&cTen gracz nie może otrzymać przepustki do tej działki.",
    "&6&lAegisGuard Staff Health Check": "&6&lKontrola zdrowia staffu AegisGuard",
    "&6Admin Update": "&6Aktualizacja admina",
    "&aEnabled": "&aWłączone",
    "&cDisabled": "&cWyłączone",
    "Server Warp": "Warp serwera",
    "Category: {CATEGORY}": "Kategoria: {CATEGORY}",
    "&7Likes: &d{LIKES} &8| &7Visits: &b{VISITS}": "&7Polubienia: &d{LIKES} &8| &7Wizyty: &b{VISITS}",
    "&6★ Featured Territory": "&6★ Wyróżnione terytorium",
    "&eRight-click to favorite": "&ePPM, aby dodać do ulubionych",
    "&eRight-click to remove favorite": "&ePPM, aby usunąć z ulubionych",
    "Unknown": "Nieznany",
    "&aJoin {GROUP}": "&aDołącz do {GROUP}",
    "None": "Brak",
    "No staff health issues detected.": "Nie wykryto problemów zdrowia staffu.",
    "&aFirst corner selected: &f{X}, {Y}, {Z}": "&aPierwszy narożnik zaznaczony: &f{X}, {Y}, {Z}",
    "&bSecond corner selected: &f{X}, {Y}, {Z}": "&bDrugi narożnik zaznaczony: &f{X}, {Y}, {Z}",
    "&7Selection area: &e{AREA} blocks &7- use &a{COMMAND} &7to confirm.": "&7Obszar zaznaczenia: &e{AREA} bloków &7- użyj &a{COMMAND} &7aby potwierdzić.",
    "&eYour rental expires in less than {HOURS} hour(s). Use &b/ag rental renew&e.": "&eTwój wynajem wygasa za mniej niż {HOURS} godz. Użyj &b/ag rental renew&e.",
    "&aRental auto-renewed for &e{DAYS} day(s)&a.": "&aWynajem odnowiony automatycznie na &e{DAYS} dzień/dni&a.",
    "&aYour plot was rented by &f{PLAYER}&a for &e{DAYS} day(s)&a.": "&aTwoja działka została wynajęta przez &f{PLAYER}&a na &e{DAYS} dzień/dni&a.",
    "&8[&bAegisGuard&8] &7Notification Settings:": "&8[&bAegisGuard&8] &7Ustawienia powiadomień:",
    " &7- Plot Greetings: {STATE}": " &7- Powitania działki: {STATE}",
    " &7- Admin Updates: {STATE}": " &7- Aktualizacje admina: {STATE}",
    " &7- Mode: &b{MODE}": " &7- Tryb: &b{MODE}",
}

MANUAL["old_english"] = {
    "&aAegisGuard reload complete.": "&aAegisGuard hath been reloaded.",
    "&6Bypass Mode: {STATE}": "&6Bypass Mode: {STATE}",
    "&cThe audit ledger is unavailable.": "&cThe audit ledger is sealed.",
    "&eYou already have an Aegis claim wand or Sentinel's Scepter.": "&eThou already bearest an Aegis claim wand or Sentinel's Scepter.",
    "&aYou received the Sentinel's Scepter.": "&aThou hast received the Sentinel's Scepter.",
    "&7Select two corners, then use &b/agadmin claim&7.": "&7Mark two corners, then use &b/agadmin claim&7.",
    "&cMigration wand is unavailable.": "&cThe migration wand is unavailable.",
    "&cYou need to select two corners first with the Sentinel's Scepter.": "&cThou must first mark two corners with the Sentinel's Scepter.",
    "&7Use &b/agadmin wand server &7to get it.": "&7Use &b/agadmin wand server &7to claim it.",
    "&cStand inside the server zone you want to manage.": "&cStand within the server zone thou wouldst manage.",
    "&aFirst corner selected: &f{X}, {Y}, {Z}": "&aFirst corner marked: &f{X}, {Y}, {Z}",
    "&bSecond corner selected: &f{X}, {Y}, {Z}": "&bSecond corner marked: &f{X}, {Y}, {Z}",
    "&7Selection area: &e{AREA} blocks &7- use &a{COMMAND} &7to confirm.": "&7Marked area: &e{AREA} blocks &7- use &a{COMMAND} &7to confirm.",
    "&cEnter a valid Minecraft player name.": "&cSpeak a true Minecraft player name.",
    "&cThat player has not played on this server.": "&cThat player hath not walked this realm.",
    "&cThat player cannot receive a pass for this plot.": "&cThat player may not receive a pass for this holding.",
    "&6Admin Update": "&6Admin Tidings",
    "No staff health issues detected.": "No staff health ills were found.",
    "&eYour rental expires in less than {HOURS} hour(s). Use &b/ag rental renew&e.": "&eThy rental expires in less than {HOURS} hour(s). Use &b/ag rental renew&e.",
    "&8[&bAegisGuard&8] &7Notification Settings:": "&8[&bAegisGuard&8] &7Notification Settings:",
    " &7- Plot Greetings: {STATE}": " &7- Holding Greetings: {STATE}",
    " &7- Admin Updates: {STATE}": " &7- Admin Tidings: {STATE}",
}
